framework:
    messenger:
        default_bus: messenger.produce.bus

        buses:
            messenger.produce.bus:
                middleware:
                  - 'messenger.middleware.validation'
            messenger.consume.bus:
                middleware:
                  - 'App\Middleware\DeduplicationMiddleware'

        transports:
            gitlab.command: enqueue://default?queue[name]=gitlab&topic[name]=gitlab
            jira.command: enqueue://default?queue[name]=jira&topic[name]=jira

        routing:
            'App\Message\Gitlab\MrMessage': gitlab.command
            'App\Message\Jira\TransitionMessage': jira.command
