version: '3'
services:
    php:
        build: ./docker/php
        container_name: messenger-demo-php
        ports:
            - '80:80'
        tty: true
        volumes:
            - .:/var/www/symfony:cached
        depends_on:
            - rabbitmq
            - mysql
            - redis
    rabbitmq:
        image: rabbitmq:3-management
        container_name: messenger-demo-rabbitmq
        ports:
            - '15672:15672'
            - '5672:5672'
    mysql:
        image: mysql
        container_name: messenger-demo-mysql
        ports:
          - '3306:3306'
        environment:
            MYSQL_DATABASE: mqdev
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    redis:
        image: redis
        container_name: messenger-demo-redis
        ports:
            - '6379:6379'
